#-----------------------------------------------------------------------
# Bryan Crawley
# CS3123
# Spring 2026
#
# Build the application for the bare bones demonstration of
# virtual methods.
#-----------------------------------------------------------------------

a.out: main.cpp virtual.cpp virtual.h
	g++ main.cpp virtual.cpp
clean:
	rm -f a.out
