#-------------------------------------------------------
# Bryan Crawley
# Lipscomb University
# Spring 2025
#
# This builds the stack-of-ints example.
#-------------------------------------------------------

a.out: main.cpp IntStack.h IntStack.cpp
	g++ main.cpp IntStack.cpp
clean:
	rm -f a.out *.o
