#-------------------------------------------------------
# This is minimal makefile for the Calender class
#-------------------------------------------------------

a.out: main_calender.cpp calender.cpp calender.h
	g++ main_calender.cpp calender.cpp
clean:
	rm -f a.out *.o