#-------------------------------------------------------
# This is minimal makefile for the Rational number class
#-------------------------------------------------------

a.out: main.cpp Rational.cpp Rational.h
	g++ main.cpp Rational.cpp
clean:
	rm -f a.out *.o
